web:
  build: .
  volumes:
    - ./:/usr/app/
  ports:
    - "5000:5000"
  links:
    - db
  command: >
    bash -c "
    sleep 30
    && export PYTHONPATH="${PYTHONPATH}:."
    && alembic revision --autogenerate -m "Test1"
    && alembic upgrade head
    && alembic revision --autogenerate -m "Test2""
db:
  image: postgres:9.5.0
  ports:
   - "5432:5432"